let certifications = {
    a: {
        name: 'Salesforce\nB2C Commerce Developer',
        tags: 'Developer,Commerce Cloud',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/B2C-Commerce-Developer.png',
        link: 'https://trailhead.salesforce.com/es/credentials/b2ccommercedeveloper',
        location: { x: -1, y: 0 },
        dependencies: [],
        related: [ 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    b: {
        name: 'Salesforce\nB2C Commerce Architect',
        tags: 'Architect,Commerce Cloud',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/B2C-Commerce-Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/b2ccommercearchitect',
        location: { x: 4, y: 0 },
        dependencies: [ 'a' ],
        related: [  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c: {
        name: 'B2B on Lightning Administrator',
        tags: 'Admin,Commerce Cloud',
        image: 'https://images.credly.com/size/110x110/images/803bc4e9-f159-44e2-81c3-1eebbd026f55/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/b2b-commerce-for-administrators-accredited-professional',
        location: { x: 1, y: -3 },
        dependencies: [ ],
        related: [  ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    d: {
        name: 'B2B on Lightning Developer',
        tags: 'Developer,Commerce Cloud',
        image: 'https://images.credly.com/size/110x110/images/803bc4e9-f159-44e2-81c3-1eebbd026f55/image.png',
        link: '',
        location: { x: 2, y: -3 },
        dependencies: [ 'c' ],
        related: [  ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    e: {
        name: 'Order Management Administrator',
        tags: 'Admin,Commerce Cloud',
        image: 'https://images.credly.com/size/110x110/images/9bbd7956-9afd-4f07-a435-76c23bb238c0/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/order-management-administrator-accredited-professional',
        location: { x: 1, y: -2 },
        dependencies: [ ],
        related: [  ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    f: {
        name: 'Order Management Developer',
        tags: 'Developer,Commerce Cloud',
        image: 'https://images.credly.com/size/110x110/images/ad84148c-bfe7-4911-8ec2-486d188a74b8/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/order-management-developer-accredited-professional',
        location: { x: 2, y: -2 },
        dependencies: [ 'e' ],
        related: [  ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    g: {
        name: 'Commerce Cloud Einstein',
        tags: 'AI,Commerce Cloud',
        image: 'https://images.credly.com/size/110x110/images/c7923449-9bc6-463b-8cc2-54c65bef5daf/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/commerce-cloud-einstein-accredited-professional',
        location: { x: 2, y: -1 },
        dependencies: [ ],
        related: [  ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    h: {
        name: 'Headless | API First',
        tags: 'Developer,Commerce Cloud',
        image: 'https://images.credly.com/size/110x110/images/3536affc-04cd-4324-b324-e30245e0aed9/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/headless-api-first-accredited-professional',
        location: { x: 1, y: -1 },
        dependencies: [ ],
        related: [  ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    i: {
        name: 'Salesforce\nPlatform App Builder',
        tags: 'Admin,Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Platform-App-Builder.png',
        link: 'https://trailhead.salesforce.com/es/credentials/platformappbuilder',
        location: { x: -1, y: 2 },
        dependencies: [  ],
        related: [ 'j'  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    j: {
        name: 'Salesforce\nAssociate',
        tags: 'Associate,Admin',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Associate.png',
        link: 'https://trailhead.salesforce.com/es/credentials/associate',
        location: { x: -3.5, y: 3 },
        dependencies: [  ],
        related: [  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    k: {
        name: 'Process Automation',
        tags: 'Admin,Developer',
        image: 'https://images.credly.com/size/110x110/images/2dd66638-ab67-4bb6-aa49-8462e4485611/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/process-automation-accredited-professional',
        location: { x: -1, y: 3 },
        dependencies: [  ],
        related: [ 'i'  ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    l: {
        name: 'Security & Privacy',
        tags: 'Admin',
        image: 'https://images.credly.com/size/110x110/images/ef8d3ef5-16bf-439c-84b8-27b535e227aa/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/security-privacy-accredited-professional',
        location: { x: 0, y: 4 },
        dependencies: [  ],
        related: [ 'n'],
        type: 'Accredited Professional',
        grayscale: false,
    },
    m: {
        name: 'Salesforce\nB2C Solution Architect',
        tags: 'Architect,Commerce Cloud',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/B2C-Solution-Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/b2csolutionarchitect',
        location: { x: 5, y: 2 },
        dependencies: [ 'o', 'z', 'i' ],
        related: [  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    n: {
        name: 'Salesforce\nSharing and Visibility\nArchitect',
        tags: 'Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Sharing%20and%20Visibility%20Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/sharingandvisibilityarchitect',
        location: { x: 1, y: 4 },
        dependencies: [],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    o: {
        name: 'Salesforce\nData Architect',
        tags: 'Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Data%20Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/dataarchitect',
        location: { x: 4, y: 3 },
        dependencies: [],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    p: {
        name: 'Salesforce\nApplication Architect',
        tags: 'Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Application-Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/applicationarchitect',
        location: { x: 3, y: 4 },
        dependencies: [ 'n', 'o', 'i', 's' ],
        related: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    q: {
        name: 'Salesforce\nB2B Solution Architect',
        tags: 'Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/B2B-Solution-Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/b2bsolutionarchitect',
        location: { x: 5, y: 4 },
        dependencies: [ 'p' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    r: {
        name: 'Salesforce\nTechnical Architect',
        tags: 'Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Technical-Architect.png',
        link: 'https://trailhead.salesforce.com/en/credentials/technicalarchitect',
        location: { x: 3, y: 6 },
        dependencies: [ 'p', 'u' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    s: {
        name: 'Salesforce\nPlatform Developer I',
        tags: 'Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Platform-Developer-I.png',
        link: 'https://trailhead.salesforce.com/es/credentials/platformdeveloperi',
        location: { x: -1, y: 7 },
        dependencies: [],
        related: [ 't', 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    t: {
        name: 'Salesforce\nJavaScript Developer I',
        tags: 'Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/JavaScript-Developer-I.png',
        link: 'https://trailhead.salesforce.com/es/credentials/javascriptdeveloperi',
        location: { x: -1, y: 6 },
        dependencies: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    u: {
        name: 'Salesforce\nSystem Architect',
        tags: 'Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/System-Architect.png',
        link: 'https://trailhead.salesforce.com/en/credentials/systemarchitect',
        location: { x: 3, y: 8 },
        dependencies: [ 's', 'w', 'x', 'z' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    v: {
        name: 'Salesforce\nPlatform Developer II',
        tags: 'Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Platform-Developer-II.png',
        link: 'https://trailhead.salesforce.com/es/credentials/platformdeveloperii',
        location: { x: -1, y: 8 },
        dependencies: [ 's' ],
        related: [  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    w: {
        name: 'Salesforce\nIdentity and Access\nManagement Architect',
        tags: 'Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/ID%20and%20Access%20Mgmt%20Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/identityandaccessmanagementarchitect',
        location: { x: 2, y: 9 },
        dependencies: [],
        related: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    x: {
        name: 'Salesforce\nDevelopment Lifecycle and\n Deployment Architect',
        tags: 'Architect,Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Dev%20Lifecycle%20and%20Deploy%20Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/developmentlifecycledeploymentarchitect',
        location: { x: 4, y: 9 },
        dependencies: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    z: {
        name: 'Salesforce\nIntegration Architect',
        tags: 'Architect,Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Integration%20Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/integrationarchitect',
        location: { x: 7, y: 4 },
        dependencies: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    aa: {
        name: 'Salesforce\nAI Associate',
        tags: 'Associate,Admin,AI',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/ai-associate.png?v=2',
        link: 'https://trailhead.salesforce.com/es/credentials/aiassociate',
        location: { x: -6, y: -3 },
        related: [ 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ab: {
        name: 'Einstein\nNext Best Action\n(Retired)',
        tags: 'AI',
        image: 'https://images.credly.com/size/110x110/images/489cff03-5c83-4a2c-824f-c7c2b720ef02/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/einstein-next-best-action-accredited-professional',
        location: { x: -6.5, y: -4 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    ac: {
        name: 'Einstein Prediction Builder',
        tags: 'AI',
        image: 'https://images.credly.com/size/110x110/images/871a058d-5383-4066-bc5e-eb00a9dba7fa/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/einstein-prediction-builder-accredited-professional',
        location: { x: -7, y: -3 },
        dependencies: [  ],
        related: [ 'aa' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    ad: {
        name: 'Einstein Discovery\n(Retired)',
        tags: 'AI',
        image: 'https://images.credly.com/size/110x110/images/6a5f325b-ad82-40ad-a668-01b57ddd06a4/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/einstein-discovery-accredited-professional',
        location: { x: -7.5, y: -4 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    ae: {
        name: 'Tableu CRM &\nEinstein Discovery Consultant',
        tags: 'AI',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Tableau-CRM-and-Einstein-Discovery-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/tableaucrmandeinsteindiscoveryconsultant',
        location: { x: -8, y: -3 },
        dependencies: [  ],
        related: [ 'ac' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    af: {
        name: 'Salesforce\nUser Experience (UX) Designer',
        tags: 'Designer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/UX%20Designer.png',
        link: 'https://trailhead.salesforce.com/es/credentials/userexperiencedesigner',
        location: { x: -6, y: -1 },
        dependencies: [  ],
        related: [ 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ag: {
        name: 'Salesforce\nStrategy Designer',
        tags: 'Designer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Strategy%20Designer.png',
        link: 'https://trailhead.salesforce.com/es/credentials/strategydesigner',
        location: { x: -6, y: 0 },
        dependencies: [  ],
        related: [ 'j', 'ah' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ah: {
        name: 'Salesforce\nSales Representative',
        tags: 'Sales Cloud',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Sales-Representative.png',
        link: 'https://trailhead.salesforce.com/es/credentials/salesrepresentative',
        location: { x: -6, y: 1 },
        dependencies: [  ],
        related: [ 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ai: {
        name: 'Salesforce\nAdmin',
        tags: 'Admin',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Administrator.png',
        link: 'https://trailhead.salesforce.com/es/credentials/administrator',
        location: { x: -6, y: 7 },
        dependencies: [  ],
        related: [ 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    aj: {
        name: 'Salesforce\nAdvanced Admin',
        tags: 'Admin',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Advanced-Administrator.png',
        link: 'https://trailhead.salesforce.com/es/credentials/advancedadministrator',
        location: { x: -8, y: 6 },
        dependencies: [ 'ai' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ak: {
        name: 'Salesforce\nSales Cloud\nConsultant',
        tags: 'Consultant',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Sales-Cloud-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/salescloudconsultant',
        location: { x: -8, y: 0 },
        dependencies: [ 'ai' ],
        related: [ 'ah' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    al: {
        name: 'Salesforce Maps',
        tags: 'Sales Cloud',
        image: 'https://images.credly.com/size/110x110/images/1f6f235c-c3bf-4d45-bd8f-2beaedb1d36d/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/salesforce-maps-accredited-professional',
        location: { x: -9, y: -0.5 },
        dependencies: [  ],
        related: [ 'ak' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    am: {
        name: 'Sales Cloud Einstein\n(Retired)',
        tags: 'Sales Cloud,AI',
        image: 'https://images.credly.com/size/110x110/images/acb0e269-d560-42ce-9584-94ef3652167c/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/sales-cloud-einstein-accredited-professional',
        location: { x: -10, y: -1.5 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    an: {
        name: 'Salesforce\nService Cloud\nConsultant',
        tags: 'Consultant,Service Cloud',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Service-Cloud-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/servicecloudconsultant',
        location: { x: -8, y: 3 },
        dependencies: [ 'ai' ],
        related: [  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ao: {
        name: 'Service Cloud Einstein',
        tags: 'Service Cloud,AI',
        image: 'https://images.credly.com/size/110x110/images/6c0ce4b5-192a-4e52-bd6d-c50a345cca69/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/service-cloud-einstein-accredited-professional',
        location: { x: -9, y: 1.5 },
        dependencies: [  ],
        related: [ 'an' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    ap: {
        name: 'Contact Center',
        tags: 'Service Cloud',
        image: 'https://images.credly.com/size/110x110/images/1e8b9739-49af-42a0-ade9-9491667e0708/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/contact-center-accredited-professional',
        location: { x: -9, y: 2.5 },
        dependencies: [  ],
        related: [ 'an' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    aq: {
        name: 'Salesforce\nField Service\nConsultant',
        tags: 'Consultant,Service Cloud',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Field-Service-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/fieldserviceconsultant',
        location: { x: -9, y: 3.5 },
        dependencies: [  ],
        related: [ 'an'  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ar: {
        name: 'Salesforce\nOmniStudio Developer',
        tags: 'Developer,Service Cloud,Sales Cloud',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/OmniStudio-Developer.png',
        link: 'https://trailhead.salesforce.com/es/credentials/omnistudiodeveloper',
        location: { x: -9, y: 4.5 },
        dependencies: [],
        related: [ 'an' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    as: {
        name: 'Salesforce\nOmniStudio Consultant',
        tags: 'Consultant',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/OmniStudio-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/omnistudioconsultant',
        location: { x: -10, y: 4.5 },
        dependencies: [],
        related: [ 'ar' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    at: {
        name: 'Advanced Field Service',
        tags: 'Service Cloud',
        image: 'https://images.credly.com/size/110x110/images/91ae0cb8-8329-44a8-85a6-7896bbae4324/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/advanced-field-service-accredited-professional',
        location: { x: -10, y: 3.5 },
        dependencies: [  ],
        related: [ 'aq' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    au: {
        name: 'Salesforce\nBusiness Analyst',
        tags: 'Admin',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Business%20Analyst.png',
        link: 'https://trailhead.salesforce.com/es/credentials/businessanalyst',
        location: { x: -10, y: 6 },
        dependencies: [ ],
        related: [  'aj' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    av: {
        name: 'Salesforce\nCPQ Specialist',
        tags: 'Admin',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/CPQ-Specialist.png',
        link: 'https://trailhead.salesforce.com/es/credentials/cpqspecialist',
        location: { x: -8, y: 7 },
        dependencies: [ ],
        related: [ 'ai' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    aw: {
        name: 'Salesforce\nIndustries CPQ Developer',
        tags: 'Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Industries-CPQ-Developer.png',
        link: 'https://trailhead.salesforce.com/es/credentials/industriescpqdeveloper',
        location: { x: -9, y: 7 },
        related: [ 'av' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ax: {
        name: 'Salesforce\nExperience Cloud\nConsultant',
        tags: 'Consultant',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Experience-Cloud-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/experiencecloudconsultant',
        location: { x: -8, y: 8 },
        related: [ 'ai' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ay: {
        name: 'Salesforce\nCMS',
        tags: 'Consultant',
        image: 'https://images.credly.com/size/110x110/images/8129837f-407d-4055-9aa3-c1808ba5aa8e/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/salesforce-cms-accredited-professional',
        location: { x: -9, y: 8 },
        related: [ 'ax' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    az: {
        name: 'Salesforce\nNonprofit Cloud\nConsultant',
        tags: 'Consultant',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Nonprofit-Cloud-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/nonprofitcloudconsultant',
        location: { x: -8, y: 9 },
        dependencies: [],
        related: [ 'ai' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    ba: {
        name: 'Mobile',
        tags: 'Developer,Admin',
        image: 'https://images.credly.com/size/110x110/images/5f983f1d-efcc-4ced-8866-8ea9c0ddd05c/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/salesforce-mobile-accredited-professional',
        location: { x: -8, y: 10 },
        dependencies: [  ],
        related: [ 'ai' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    bb: {
        name: 'Salesforce Data Cloud\nConsultant',
        tags: 'Consultant,Admin',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/datacloudconsultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/datacloudconsultant',
        location: { x: -8, y: 12 },
        dependencies: [  ],
        related: [ 'ai' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    bc: {
        name: 'Marketing Cloud\nAccount Engagement\nBusiness Units',
        tags: 'Consultant,Admin',
        image: 'https://images.credly.com/size/110x110/images/eb05342a-1ba9-4722-86bc-934cb9345f54/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/marketing-cloud-account-engagement-business-units-accredited-professional',
        location: { x: -6, y: 12 },
        dependencies: [  ],
        related: [ 'ai', 'be' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    bd: {
        name: 'Marketing Cloud\nAccount Engagement\nReporting & Analytics',
        tags: 'Consultant,Admin',
        image: 'https://images.credly.com/size/110x110/images/eb05342a-1ba9-4722-86bc-934cb9345f54/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/marketing-cloud-account-engagement-business-units-accredited-professional',
        location: { x: -5, y: 12 },
        dependencies: [  ],
        related: [ 'ai', 'be' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    be: {
        name: 'Salesforce\nMarketing Cloud\nAccount Engagement\nSpecialist',
        tags: 'Marketer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/marketing-cloud-account-engagement-specialist.png',
        link: 'https://trailhead.salesforce.com/es/credentials/marketingcloudaccountengagementspecialist',
        location: { x: -5, y: 11 },
        dependencies: [],
        related: [ 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    bf: {
        name: 'Salesforce\nMarketing Cloud\nAccount Engagement\nConsultant',
        tags: 'Marketer,Consultant,Admin',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/marketing-cloud-account-engagement-consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/marketingcloudaccountengagementconsultant',
        location: { x: -4, y: 12 },
        dependencies: [ 'be' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    bg: {
        name: 'Salesforce\nMarketing Cloud\nConsultant',
        tags: 'Marketer,Consultant',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Marketing-Cloud-Consultant.png',
        link: 'https://trailhead.salesforce.com/es/credentials/marketingcloudconsultant',
        location: { x: -1, y: 11 },
        dependencies: [ 'bi' ],
        related: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    bh: {
        name: 'Salesforce\nMarketing Cloud\nEmail Specialist',
        tags: 'Marketer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Marketing-Cloud-Email-Specialist.png',
        link: 'https://trailhead.salesforce.com/es/credentials/marketingcloudemailspecialist',
        location: { x: -3, y: 12 },
        related: [  ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    bi: {
        name: 'Salesforce\nMarketing Cloud\nAdministrator',
        tags: 'Admin,Marketer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Marketing-Cloud-Administrator.png',
        link: 'https://trailhead.salesforce.com/es/credentials/marketingcloudadministrator',
        location: { x: -3, y: 11 },
        dependencies: [],
        related: [ 'j' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    bj: {
        name: 'Salesforce\nMarketing Cloud\nDeveloper',
        tags: 'Marketer,Developer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Marketing-Cloud-Developer.png',
        link: 'https://trailhead.salesforce.com/es/credentials/marketingclouddeveloper',
        location: { x: -2, y: 12 },
        dependencies: [ 'bh' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    bk: {
        name: 'Advanced Cross Channel',
        tags: 'Marketer,Consultant,Developer',
        image: 'https://images.credly.com/size/110x110/images/43576eaa-541e-4e75-b2ac-f910e4cd2d8f/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/marketing-cloud-advanced-cross-channel-accredited-professional',
        location: { x: -1, y: 12 },
        dependencies: [  ],
        related: [ 'bj', 'bg' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c1: {
        name: 'Manufacturing Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/4082c47c-6633-4a16-94e0-118099d58ab1/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/manufacturing-cloud-accredited-professional',
        location: { x: -13, y: 0 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c2: {
        name: 'Media Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/66cfc7bd-6e42-454f-a512-e3bdc18176c4/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/media-cloud-accredited-professional',
        location: { x: -14, y: 0 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c3: {
        name: 'Health Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/54ff6116-9488-4145-9a2e-17de0a3259c0/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/health-cloud-accredited-professional',
        location: { x: -13, y: 1 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c4: {
        name: 'Net Zero Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/d31ac878-9b99-40a5-b0af-3fff2a5883c9/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/net-zero-cloud-accredited-professional',
        location: { x: -14, y: 1 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c5: {
        name: 'Education Cloud Consultant',
        tags: 'Industries,Consultant',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Education-Cloud-Consultant.png',
        link: 'https://trailhead.salesforce.com/en/credentials/educationcloudconsultant',
        location: { x: -8, y: 11 },
        dependencies: [  ],
        related: [ 'ai' ],
        type: 'credential',
        grayscale: false,
    },
    c7: {
        name: 'Consumer Goods Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/9906d717-89a9-4892-85f0-8075939fe96c/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/consumer-goods-cloud-accredited-professional',
        location: { x: -13, y: 2 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c8: {
        name: 'Financial Services Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/c4d50ba4-a0db-4932-a7b1-69fd70214e13/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/financial-services-cloud-accredited-professional',
        location: { x: -14, y: 2 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c9: {
        name: 'Revenue Cloud Consultant',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/65443735-ee75-47c1-93a1-76dfd6c52746/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/revenue-cloud-consultant-accredited-professional',
        location: { x: -10, y: 7 },
        dependencies: [  ],
        related: [ 'aw' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c10: {
        name: 'Communications Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/ed875b07-7937-4ad1-abbe-443f32524a22/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/communications-cloud-accredited-professional',
        location: { x: -14, y: 3 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c11: {
        name: 'Energy and Utilities Cloud',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/a4900289-0113-403c-b33d-ed959f234d38/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/energy-and-utilities-cloud-accredited-professional',
        location: { x: -13, y: 3 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c12: {
        name: 'Public Sector Solutions',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/2d9e4883-adbe-413d-8a3f-05387e783f90/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/public-sector-solutions-accredited-professional',
        location: { x: -14, y: 4 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c15: {
        name: 'Loyalty Management',
        tags: 'Industries',
        image: 'https://images.credly.com/size/110x110/images/8fd3e143-9116-4358-8863-58a53051b2ea/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/loyalty-management-accredited-professional',
        location: { x: -13, y: 4 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c16: {
        name: 'Digital Engagement\n(Retired)',
        tags: 'Service Cloud',
        image: 'https://images.credly.com/size/110x110/images/a8c2c64d-f05a-4808-9abf-3cc80570abff/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/digital-engagement-accredited-professional',
        location: { x: -10, y: 2.5 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c17: {
        name: 'Service Cloud Voice\n(Retired)',
        tags: 'Service Cloud',
        image: 'https://images.credly.com/size/110x110/images/b4869928-14c0-4499-a823-2be8b226b06d/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/service-cloud-voice-accredited-professional',
        location: { x: -10, y: 1.5 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c18: {
        name: 'Workforce Engagement\n(Retired)',
        tags: 'Sales Cloud',
        image: 'https://images.credly.com/size/110x110/images/acb88d9d-79b6-41bf-abdd-5c3fe59c9572/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/workforce-engagement-accredited-professional',
        location: { x: -10, y: 0.5 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c19: {
        name: 'Indirect Sales',
        tags: 'Sales Cloud',
        image: 'https://images.credly.com/size/110x110/images/ed3a468f-f999-4809-9cb6-f7192f0dd325/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/indirect-sales-accredited-professional',
        location: { x: -9, y: -1.5 },
        dependencies: [  ],
        related: [ 'ak' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c20: {
        name: 'Sales Business Excellence',
        tags: 'Sales Cloud',
        image: 'https://images.credly.com/size/110x110/images/84fb541f-e4b4-46d3-8d44-a7da512a29f5/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/sales-business-excellence-accredited-professional',
        location: { x: -10, y: -0.5 },
        dependencies: [  ],
        related: [ 'ak' ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c21: {
        name: 'Service Business Excellence',
        tags: 'Service Cloud',
        image: 'https://images.credly.com/size/110x110/images/39afb8bb-2731-47ad-ac2e-806642b32bd6/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/service-business-excellence-accredited-professional',
        location: { x: -9, y: 0.5 },
        dependencies: [  ],
        related: [ 'an'],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c22: {
        name: 'Mulesoft Integration Associate',
        tags: 'Associate,Mulesoft,Associate',
        image: 'https://training.mulesoft.com/att/b0a641aa-5ae6-11ed-b5a6-0cc47a352292.svg',
        link: 'https://training.mulesoft.com/certification/associate-integration',
        location: { x: -14, y: 6 },
        dependencies: [  ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c23: {
        name: 'Mulesoft Developer\nLevel I',
        tags: 'Developer,Mulesoft',
        image: 'https://training.mulesoft.com/att/650ae8a6-35e6-11ed-b5a6-0cc47a352292.png',
        link: 'https://training.mulesoft.com/certification/developer-mule4-level1',
        location: { x: -14, y: 7 },
        dependencies: [  ],
        related: [ 'c22' ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c24: {
        name: 'Mulesoft Developer\nLevel II',
        tags: 'Developer,Mulesoft',
        image: 'https://training.mulesoft.com/att/388c8507-35e9-11ed-b5a6-0cc47a352292.png',
        link: 'https://training.mulesoft.com/certification/developer-mule4-level2',
        location: { x: -14, y: 8 },
        dependencies: [ 'c23' ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c25: {
        name: 'MuleSoft\nHyperautomation Specialist',
        tags: 'Mulesoft',
        image: 'https://training.mulesoft.com/att/cb9f3cb3-9393-11ed-b5a6-0cc47a352292.png',
        link: 'https://training.mulesoft.com/certification/hyperautomation-specialist',
        location: { x: -14, y: 9 },
        dependencies: [ ],
        related: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c26: {
        name: 'MuleSoft\nCatalyst Specialist',
        tags: 'Mulesoft',
        image: 'https://training.mulesoft.com/att/cb9f3cb3-9393-11ed-b5a6-0cc47a352292.png',
        link: 'https://training.mulesoft.com/certification/catalyst-specialist',
        location: { x: -13, y: 7 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c27: {
        name: 'MuleSoft\nPlatform Architect\nLevel 1',
        tags: 'Mulesoft,Architect',
        image: 'https://training.mulesoft.com/att/cb9f3cb3-9393-11ed-b5a6-0cc47a352292.png',
        link: 'https://training.mulesoft.com/certification/architect-platform-level1',
        location: { x: -13, y: 8 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c28: {
        name: 'MuleSoft\nIntegration Architect\nLevel 1',
        tags: 'Mulesoft,Architect',
        image: 'https://training.mulesoft.com/att/cb9f3cb3-9393-11ed-b5a6-0cc47a352292.png',
        link: 'https://training.mulesoft.com/certification/architect-integration-level1',
        location: { x: -13, y: 9 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c29: {
        name: 'Tableau\nArchitect',
        tags: 'Tableau,Architect',
        image: 'https://www.tableau.com/sites/default/files/2023-02/2023-01_Badge_Tab-Cert_Tab-Architect_High-Res.png',
        link: 'https://www.tableau.com/learn/certification/certified-architect',
        location: { x: -14, y: -3 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c30: {
        name: 'Tableau\nConsultant',
        tags: 'Tableau,Consultant',
        image: 'https://www.tableau.com/sites/default/files/2023-02/2023-01_Badge_Tab-Cert_Tab-Consultant_High-Res.png',
        link: 'https://www.tableau.com/learn/certification/certified-consultant',
        location: { x: -13, y: -4 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c31: {
        name: 'Tableau\nServer Associate',
        tags: 'Tableau',
        image: 'https://www.tableau.com/sites/default/files/2023-02/2023-01_Badge_Tab-Cert_Tab-Server-Associate_High-Res.png',
        link: 'https://www.tableau.com/learn/certification/server-certified-associate',
        location: { x: -13, y: -3 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c32: {
        name: 'Tableau\nData Analyst',
        tags: 'Tableau',
        image: 'https://www.tableau.com/sites/default/files/2023-02/2022-11_Badge_Tab-Cert_Data-Analyst_High-Res.png',
        link: 'https://www.tableau.com/learn/certification/certified-data-analyst',
        location: { x: -14, y: -4 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c33: {
        name: 'Tableau\nDesktop Specialist',
        tags: 'Tableau',
        image: 'https://www.tableau.com/sites/default/files/2023-02/2023-01_Badge_Tab-Cert_Desktop-Specialist_High-Res.png.png',
        link: 'https://www.tableau.com/learn/certification/desktop-specialist',
        location: { x: -12, y: -4 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c34: {
        name: 'Slack Admin',
        tags: 'Slack,Admin',
        image: 'https://templates.images.credential.net/16143954232533241495569101930499.png',
        link: 'https://badges.slackcertified.com/group/250092',
        location: { x: -14, y: 12 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c35: {
        name: 'Slack Consultant',
        tags: 'Slack,Consultant',
        image: 'https://templates.images.credential.net/16597438686206372335540931008178.png',
        link: 'https://badges.slackcertified.com/group/390301',
        location: { x: -13, y: 12 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c36: {
        name: 'Slack Developer',
        tags: 'Slack,Developer',
        image: 'https://templates.images.credential.net/16143956264688304261282565716551.png',
        link: 'https://badges.slackcertified.com/group/250520',
        location: { x: -12, y: 12 },
        dependencies: [ ],
        related: [ ],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c37: {
        name: 'Salesforce\nHeroku Architect',
        tags: 'Heroku,Architect',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/Heroku%20Architect.png',
        link: 'https://trailhead.salesforce.com/es/credentials/herokuarchitect',
        location: { x: -3.5, y: -4 },
        related: [ 'c38' ],
        dependencies: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c38: {
        name: 'Salesforce\nHeroku Developer',
        tags: 'Heroku,Developer',
        image: 'https://images.credly.com/size/110x110/images/f4fae945-7f80-4d08-8f62-55ca93bba5aa/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/heroku-developer-accredited-professional',
        location: { x: -3.5, y: -3 },
        dependencies: [],
        type: 'Saleforce Certification',
        grayscale: false,
    },
    c39: {
        name: 'Marketing Cloud\nIntelligence',
        tags: 'Consultant,Admin,Marketer',
        image: 'https://images.credly.com/size/110x110/images/3198e9d6-4d93-46c2-808e-84fdb7c20bb1/image.png',
        link: 'https://www.credly.com/org/salesforce-ap/badge/marketing-cloud-intelligence-accredited-professional',
        location: { x: -7, y: 12 },
        dependencies: [  ],
        related: [ ],
        type: 'Accredited Professional',
        grayscale: false,
    },
    c40: {
        name: 'Marketing Cloud\nAssociate',
        tags: 'Admin,Marketer',
        image: 'https://developer.salesforce.com/resources2/certification-site/images/Certifications-logo/MarketingAssociate.png',
        link: 'https://trailhead.salesforce.com/en/credentials/marketingassociate',
        location: { x: -5, y: 10 },
        dependencies: [  ],
        related: [ 'bi' ],
        type: 'Salesforce Certification',
        grayscale: false,
    },
}




// eslint-disable-next-line
let certifications_old = {
}





let edges = [];
// dependency
Object.keys(certifications).forEach(nodeKey => {
    const dependencies = certifications[nodeKey].dependencies;
    if (dependencies && dependencies.length > 0) {
        dependencies.forEach(dependencyKey => {
            edges.push({ source: dependencyKey, target: nodeKey });
        });
    }
});
// related
Object.keys(certifications).forEach(nodeKey => {
    const dependencies = certifications[nodeKey].related;
    if (dependencies && dependencies.length > 0) {
        dependencies.forEach(dependencyKey => {
            edges.push({ source: dependencyKey, target: nodeKey, animate: true });
        });
    }
});

export default {
    certifications,
    personal_connections: edges
}